### ISSUE TITLE
Breaking HA version 0.91+

### ISSUE THREAD

**Issue by ykii** [ruuvi-friends/ruuvi_hass#1]
It seems that this component is no longer working, maybe because missing manifest.json

Is it possible to add missing file to repository?

**Comment by reetzjonas** [comment]
Hi,

sorry for the late response. At the moment I dont have HA running anymore. But I will do a new setup in the next time. Then I will take a look at the problem.

**Comment by peltsippi** [comment]
See my report to ruuvitag-sensor -component that covers similar issue

https://github.com/pschumi/ruuvitag-sensor/issues/3
> Since HA 0.91 the custom components folder structure has changed, see
> https://community.home-assistant.io/t/breaking-changes-in-0-91/109772
> and
> https://developers.home-assistant.io/blog/2019/04/12/new-integration-structure.html
> 
> Copying ruuvitag.py to .homeassistant/custom_components/ruuvitag/sensor.py and creating init.py by stripping everything except REQUIREMENTS -line from original ruuvitag.py seems to do the trick at least for me 0.92.2

**Comment by PieterGit** [comment]
I'm working on a Pull request to get it work with latest HA. 
See https://github.com/JonasR-/ruuvi_hass/pull/2
Help is appreciated.
